const icon ={
    eatmelogo:require('../assets/icon/mainlogo.png'),
    check_tick:require('../assets/icon/check_tick.png'),
    wrong:require('../assets/icon/wrong.png'),
    mainlogo:require('../assets/icon/food.png'),
    mainlogo2:require('../assets/icon/food2.png'),
    mainlogo3:require('../assets/icon/food3.png'),
    left_arrow:require('../assets/icon/left_arrow.png'),
    profile:require('../assets/icon/profile.png'),
    lock:require('../assets/icon/lock.png'),
    filter:require('../assets/icon/filter.png'),
    notification:require('../assets/icon/notification.png'),
    stock:require('../assets/icon/stock.png'),
    worldicon:require('../assets/icon/worldicon.png'),
    call:require('../assets/icon/call.png'),
    shield:require('../assets/icon/shield.png'),
    door:require('../assets/icon/logout.png'),
    update:require('../assets/icon/update.png'),
    list:require('../assets/icon/list.png'),
    eye:require('../assets/icon/eye.png'),
}
export default icon