import { StyleSheet } from "react-native";
import { FONTS, selectedTheme } from "../../config";
import { COLORS } from "../../config/constants/theme";

const styles=(selectedTheme:any)=>StyleSheet.create({
    MainConatiner:{
        flex:1,
        backgroundColor:selectedTheme.backgroundwhiteNgray8
    },
    container:{
        flex:1,
        justifyContent:"center",
        marginHorizontal:"7%"

    },
    bgimage:{
        height:"40%",
        width:"100%",
        position:"absolute"
    },
    input:{
        marginVertical:"5%"
    },
    heading:{

        alignSelf:"center",
        marginVertical:10,
        fontSize:30,
        fontWeight:"700",
        ...FONTS.heading,
        color:selectedTheme.textblackNwhite
    },
    inputecontainer:{
        borderBottomWidth:1,
        borderColor:selectedTheme.lineDivider,
        flexDirection:"row"
        
    },
    eyecontainer:{
        alignSelf:"center",
    },
    eyeicon:{
        width:20,
        height:20,
        alignSelf:"center",
        resizeMode:"contain",
        tintColor:selectedTheme.tintColor,
    },
    inputText:{
        color:selectedTheme.textblackNgray,
        width:"94%",
        fontSize:15,
        ...FONTS.heading
    },
    socialbuttonsContainer:{
        flexDirection:"row",
        justifyContent:"space-around",
        marginVertical:10
    },
    socialbuttons:{
        flexDirection:"row",
        alignContent:"center",
        justifyContent:"center",
       backgroundColor:COLORS.gray10,
       width:"40%",
       borderRadius:90
    },
    buttonsContainer:{
        flexDirection:"row",
        justifyContent:"center",
        marginVertical:10
    },
    formtext:{
        fontSize:16,
        fontWeight:"700",
        color:COLORS.gray20,
        ...FONTS.heading

    },
    buttontext:{
        fontSize:17,
        color:selectedTheme.textwhite,
        fontWeight:"800",
        ...FONTS.heading
    },
    text:{
        alignSelf:"center",
        fontSize:15,
        color:selectedTheme.textblackNgray,
        ...FONTS.body
    },
    button:{
        borderRadius:90,
        backgroundColor:COLORS.primary,
        alignItems:"center",
        padding:10,
        marginVertical:10
    },
    socialbuttonstext:{
        marginHorizontal:10,
        marginVertical:12,
         fontWeight:"600",
         alignSelf:"center",
         color:COLORS.black,
         ...FONTS.heading
    },
    signuptext:{
        alignSelf:"center",
        fontWeight:"700",
        color:COLORS.primary,
        paddingLeft:10,
        ...FONTS.heading
    },
    newusertext:{
        alignSelf:"center",
        color:selectedTheme.textblackNgray,
        ...FONTS.heading
    },
    Icon:{
        width:25,
        height:25,
        alignSelf:"center",
        resizeMode:"contain",
        marginLeft:10
    }
})

export default styles