
 const Icon={
     all: require("../../assets/icons/all.png"),
 animation : require("../../assets/icons/animation.png"),
 back : require("../../assets/icons/back.png"),
 call : require("../../assets/icons/call.png"),
 camera : require("../../assets/icons/camera.png"),
 checkbox_off : require("../../assets/icons/checkbox_off.png"),
 checkbox_off_dark : require("../../assets/icons/checkbox_off_dark.png"),
 checkbox_on : require("../../assets/icons/checkbox_on.png"),
 checkbox_on_dark : require("../../assets/icons/checkbox_on_dark.png"),
 checked : require("../../assets/icons/checked.png"),
 coding : require("../../assets/icons/coding.png"),
 comment : require("../../assets/icons/comment.png"),
 completed : require("../../assets/icons/completed.png"),
 download : require("../../assets/icons/download.png"),
 drawing : require("../../assets/icons/drawing.png"),
 education : require("../../assets/icons/education.png"),
 email : require("../../assets/icons/email.png"),
 eye : require("../../assets/icons/eye.png"),
 eye_close : require("../../assets/icons/eye_close.png"),
 facebook : require("../../assets/icons/facebook.png"),
 favourite : require("../../assets/icons/favourite.png"),
 favourite_outline : require("../../assets/icons/favourite_outline.png"),
 filter : require("../../assets/icons/filter.png"),
 google : require("../../assets/icons/google.png"),
 heart : require("../../assets/icons/heart.png"),
 heart_off : require("../../assets/icons/heart_off.png"),
 home : require("../../assets/icons/home.png"),
 illustration : require("../../assets/icons/illustration.png"),
 lock : require("../../assets/icons/lock.png"),
 media : require("../../assets/icons/media.png"),
 menu : require("../../assets/icons/menu.png"),
 mobile : require("../../assets/icons/mobile.png"),
 model_3d : require("../../assets/icons/model_3d.png"),
 networking : require("../../assets/icons/networking.png"),
 new_icon : require("../../assets/icons/new.png"),
 notification : require("../../assets/icons/notification.png"),
 original : require("../../assets/icons/original.png"),
 password : require("../../assets/icons/password.png"),
 play : require("../../assets/icons/play.png"),
 play_1 : require("../../assets/icons/play_1.png"),
 profile : require("../../assets/icons/profile.png"),
 reminder : require("../../assets/icons/reminder.png"),
 reply : require("../../assets/icons/reply.png"),
 right_arrow : require("../../assets/icons/right_arrow.png"),
 search : require("../../assets/icons/search.png"),
 send : require("../../assets/icons/send.png"),
 staff_pick : require("../../assets/icons/staff_pick.png"),
 star : require("../../assets/icons/star.png"),
 star_1 : require("../../assets/icons/star_1.png"),
 sun : require("../../assets/icons/sun.png"),
 time : require("../../assets/icons/time.png"),
 web_design : require("../../assets/icons/web_design.png"),
 left_arrow:require("../../assets/icons/left_arrow.png"),
 share:require("../../assets/icons/share.png"),
 linkedin:require("../../assets/icons/linkedin.png"),
 twitter:require("../../assets/icons/twitter.png")




}

export default {Icon}